import type { Category } from '@/types';

export const mockCategories: Category[] = [
  {
    id: 'cat_1',
    name: 'Website Themes',
    slug: 'website-themes',
    description: 'Complete website themes for any industry or niche',
    icon: 'Globe',
    productCount: 324,
    color: 'indigo',
  },
  {
    id: 'cat_2',
    name: 'Admin Templates',
    slug: 'admin-templates',
    description: 'Professional admin dashboards and control panels',
    icon: 'LayoutDashboard',
    productCount: 187,
    color: 'blue',
  },
  {
    id: 'cat_3',
    name: 'React Templates',
    slug: 'react-templates',
    description: 'Modern React application templates and boilerplates',
    icon: 'Code2',
    productCount: 256,
    color: 'cyan',
  },
  {
    id: 'cat_4',
    name: 'Flutter Templates',
    slug: 'flutter-templates',
    description: 'Cross-platform Flutter app templates and UI kits',
    icon: 'Smartphone',
    productCount: 143,
    color: 'teal',
  },
  {
    id: 'cat_5',
    name: 'WordPress Themes',
    slug: 'wordpress-themes',
    description: 'Premium WordPress themes for blogs, business, and ecommerce',
    icon: 'FileCode',
    productCount: 298,
    color: 'blue',
  },
  {
    id: 'cat_6',
    name: 'UI Kits',
    slug: 'ui-kits',
    description: 'Comprehensive UI component kits for Figma, Sketch, and React',
    icon: 'Palette',
    productCount: 175,
    color: 'purple',
  },
  {
    id: 'cat_7',
    name: 'SaaS Boilerplates',
    slug: 'saas-boilerplates',
    description: 'Full-stack SaaS starter kits with authentication and billing',
    icon: 'Rocket',
    productCount: 89,
    color: 'orange',
  },
  {
    id: 'cat_8',
    name: 'Plugins',
    slug: 'plugins',
    description: 'Powerful plugins for WordPress, WooCommerce, and more',
    icon: 'Puzzle',
    productCount: 213,
    color: 'green',
  },
  {
    id: 'cat_9',
    name: 'Source Code',
    slug: 'source-code',
    description: 'Complete application source code and scripts',
    icon: 'Terminal',
    productCount: 167,
    color: 'gray',
  },
  {
    id: 'cat_10',
    name: 'Design Assets',
    slug: 'design-assets',
    description: 'Icons, illustrations, mockups, and graphic design assets',
    icon: 'Image',
    productCount: 421,
    color: 'pink',
  },
  {
    id: 'cat_11',
    name: 'Landing Pages',
    slug: 'landing-pages',
    description: 'High-converting landing page templates for any product',
    icon: 'Layout',
    productCount: 198,
    color: 'red',
  },
  {
    id: 'cat_12',
    name: 'Email Templates',
    slug: 'email-templates',
    description: 'Professional HTML email templates for marketing campaigns',
    icon: 'Mail',
    productCount: 134,
    color: 'yellow',
  },
  {
    id: 'cat_13',
    name: 'HTML Templates',
    slug: 'html-templates',
    description: 'Static HTML5 and CSS3 website templates',
    icon: 'FileCode2',
    productCount: 152,
    color: 'blue',
  },
  {
    id: 'cat_14',
    name: 'Mobile App Templates',
    slug: 'mobile-app-templates',
    description: 'React Native, Swift, and Kotlin app templates',
    icon: 'SmartphoneIcon',
    productCount: 98,
    color: 'purple',
  },
];
