export { mockUsers } from './users';
export { mockProducts } from './products';
export { mockCategories } from './categories';
export { mockReviews } from './reviews';
export { mockOrders, getRevenueByMonth } from './orders';

export const mockNotifications = [
  {
    id: 'notif_1',
    userId: 'user_seller_1',
    type: 'sale' as const,
    title: 'New Sale!',
    message: 'You sold Nexus Dashboard to Sarah Williams for $59',
    isRead: false,
    createdAt: '2024-06-14T10:30:00Z',
    link: '/dashboard/seller/earnings',
  },
  {
    id: 'notif_2',
    userId: 'user_seller_1',
    type: 'review' as const,
    title: 'New Review',
    message: 'Sarah Williams left a 5-star review on Nexus Dashboard',
    isRead: false,
    createdAt: '2024-06-14T11:00:00Z',
    link: '/dashboard/seller/products',
  },
  {
    id: 'notif_3',
    userId: 'user_buyer_1',
    type: 'download' as const,
    title: 'Download Ready',
    message: 'Your purchase of Prism UI is ready to download',
    isRead: true,
    createdAt: '2024-06-13T15:20:00Z',
    link: '/dashboard/buyer/downloads',
  },
  {
    id: 'notif_4',
    userId: 'user_buyer_1',
    type: 'system' as const,
    title: 'Welcome to TheMeShopy!',
    message: 'Complete your profile to get personalized recommendations',
    isRead: true,
    createdAt: '2024-06-10T09:00:00Z',
  },
  {
    id: 'notif_5',
    userId: 'user_admin_1',
    type: 'system' as const,
    title: 'New Seller Registration',
    message: 'A new seller has registered and is pending approval',
    isRead: false,
    createdAt: '2024-06-14T08:00:00Z',
    link: '/dashboard/admin/sellers',
  },
  {
    id: 'notif_aff_1',
    userId: 'user_affiliate_1',
    type: 'sale' as const,
    title: 'Referral Sale Commission!',
    message: 'Sarah Williams registered via your link and purchased Aurora Landing Page Kit. You earned $8.70!',
    isRead: false,
    createdAt: '2024-06-14T12:00:00Z',
    link: '/dashboard/affiliate/earnings',
  },
  {
    id: 'notif_aff_2',
    userId: 'user_affiliate_1',
    type: 'system' as const,
    title: 'Affiliate Tier Upgraded',
    message: 'Congratulations! Your commission rate has been upgraded to 30% after reaching 5 conversions.',
    isRead: true,
    createdAt: '2024-06-12T09:00:00Z',
    link: '/dashboard/affiliate/campaigns',
  },
  {
    id: 'notif_age_1',
    userId: 'user_agency_1',
    type: 'download' as const,
    title: 'New Team Download',
    message: 'Alice Johnson downloaded Nexus - Modern SaaS Dashboard for project FinanceFlow SaaS App.',
    isRead: false,
    createdAt: '2024-06-14T14:30:00Z',
    link: '/dashboard/agency/downloads',
  },
  {
    id: 'notif_age_2',
    userId: 'user_agency_1',
    type: 'system' as const,
    title: 'Seat Allocation Alert',
    message: 'You have only 1 seat remaining on your LaunchKit - SaaS Boilerplate license key.',
    isRead: false,
    createdAt: '2024-06-13T10:00:00Z',
    link: '/dashboard/agency/licenses',
  },
  {
    id: 'notif_sell2_1',
    userId: 'user_seller_2',
    type: 'sale' as const,
    title: 'Sale Cleared',
    message: 'Your earnings for Aurora Landing Page Kit sale have cleared. $20.30 added to your account.',
    isRead: false,
    createdAt: '2024-06-14T15:00:00Z',
    link: '/dashboard/seller/earnings',
  },
];
