import type { Order } from '@/types';

export const mockOrders: Order[] = [
  {
    id: 'ord_1',
    buyerId: 'user_buyer_1',
    buyerName: 'Sarah Williams',
    buyerEmail: 'buyer@themeshopy.com',
    sellerId: 'user_seller_1',
    productId: 'prod_1',
    productTitle: 'Nexus - Modern SaaS Dashboard',
    productThumbnail: 'https://images.unsplash.com/photo-1555099962-4199c345e5dd?w=600&h=400&fit=crop&q=80',
    amount: 59,
    license: 'regular',
    status: 'completed',
    paymentMethod: 'Stripe',
    createdAt: '2024-05-15T10:30:00Z',
    downloadUrl: '/downloads/nexus-v3.2.1.zip',
  },
  {
    id: 'ord_2',
    buyerId: 'user_buyer_1',
    buyerName: 'Sarah Williams',
    buyerEmail: 'buyer@themeshopy.com',
    sellerId: 'user_seller_4',
    productId: 'prod_4',
    productTitle: 'Prism UI - React Component Library',
    productThumbnail: 'https://images.unsplash.com/photo-1547658719-da2b51169166?w=600&h=400&fit=crop&q=80',
    amount: 79,
    license: 'regular',
    status: 'completed',
    paymentMethod: 'Stripe',
    createdAt: '2024-04-22T14:20:00Z',
    downloadUrl: '/downloads/prism-ui-v5.0.2.zip',
  },
  {
    id: 'ord_3',
    buyerId: 'user_buyer_1',
    buyerName: 'Sarah Williams',
    buyerEmail: 'buyer@themeshopy.com',
    sellerId: 'user_seller_4',
    productId: 'prod_9',
    productTitle: 'IconFlow - 5000+ SVG Icons Pack',
    productThumbnail: 'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=600&h=400&fit=crop&q=80',
    amount: 39,
    license: 'regular',
    status: 'completed',
    paymentMethod: 'PayPal',
    createdAt: '2024-06-01T09:15:00Z',
    downloadUrl: '/downloads/iconflow-v7.0.0.zip',
  },
  {
    id: 'ord_4',
    buyerId: 'user_agency_1',
    buyerName: 'Digital Nexus Agency',
    buyerEmail: 'agency@themeshopy.com',
    sellerId: 'user_seller_1',
    productId: 'prod_1',
    productTitle: 'Nexus - Modern SaaS Dashboard',
    productThumbnail: 'https://images.unsplash.com/photo-1555099962-4199c345e5dd?w=600&h=400&fit=crop&q=80',
    amount: 149,
    license: 'extended',
    status: 'completed',
    paymentMethod: 'Stripe',
    createdAt: '2024-05-08T16:45:00Z',
    downloadUrl: '/downloads/nexus-v3.2.1-extended.zip',
  },
  {
    id: 'ord_5',
    buyerId: 'user_buyer_1',
    buyerName: 'Sarah Williams',
    buyerEmail: 'buyer@themeshopy.com',
    sellerId: 'user_seller_1',
    productId: 'prod_5',
    productTitle: 'LaunchKit - SaaS Boilerplate',
    productThumbnail: 'https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?w=600&h=400&fit=crop&q=80',
    amount: 149,
    license: 'regular',
    status: 'completed',
    paymentMethod: 'Stripe',
    createdAt: '2024-06-05T11:00:00Z',
    downloadUrl: '/downloads/launchkit-v2.3.0.zip',
  },
];

// Revenue analytics helper
export const getRevenueByMonth = () => [
  { month: 'Jan', revenue: 12400, orders: 187 },
  { month: 'Feb', revenue: 18200, orders: 256 },
  { month: 'Mar', revenue: 15800, orders: 223 },
  { month: 'Apr', revenue: 22100, orders: 312 },
  { month: 'May', revenue: 28400, orders: 389 },
  { month: 'Jun', revenue: 24680, orders: 342 },
];
