import type { Product } from '@/types';

const thumbnailBases = [
  'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=600&h=400&fit=crop&q=80',
  'https://images.unsplash.com/photo-1555099962-4199c345e5dd?w=600&h=400&fit=crop&q=80',
  'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=600&h=400&fit=crop&q=80',
  'https://images.unsplash.com/photo-1547658719-da2b51169166?w=600&h=400&fit=crop&q=80',
  'https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?w=600&h=400&fit=crop&q=80',
  'https://images.unsplash.com/photo-1559028012-481c04fa702d?w=600&h=400&fit=crop&q=80',
  'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=400&fit=crop&q=80',
  'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=600&h=400&fit=crop&q=80',
  'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=600&h=400&fit=crop&q=80',
  'https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=600&h=400&fit=crop&q=80',
  'https://images.unsplash.com/photo-1616469829581-73993eb86b02?w=600&h=400&fit=crop&q=80',
  'https://images.unsplash.com/photo-1622675363311-3e1904dc1885?w=600&h=400&fit=crop&q=80',
];

export const mockProducts: Product[] = [
  {
    id: 'prod_1',
    title: 'Nexus - Modern SaaS Dashboard',
    slug: 'nexus-modern-saas-dashboard',
    description: 'A premium React dashboard template with 50+ components, dark/light mode, and full TypeScript support.',
    longDescription: 'Nexus is the ultimate React dashboard template built for modern SaaS applications. Featuring 50+ pre-built components, seamless dark/light mode, comprehensive TypeScript support, and responsive layouts for every device. Perfect for admin panels, analytics dashboards, and SaaS applications.',
    price: 59,
    originalPrice: 89,
    category: 'Admin Templates',
    categorySlug: 'admin-templates',
    sellerId: 'user_seller_1',
    sellerName: 'Alex Johnson',
    sellerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face',
    thumbnail: thumbnailBases[1],
    images: [thumbnailBases[1], thumbnailBases[2], thumbnailBases[3]],
    tags: ['react', 'dashboard', 'typescript', 'tailwind', 'saas'],
    rating: 4.9,
    reviewCount: 287,
    sales: 1840,
    downloads: 1900,
    license: 'regular',
    licensePrice: 149,
    version: '3.2.1',
    lastUpdated: '2024-06-10',
    createdAt: '2023-08-15',
    isNew: false,
    isTrending: true,
    isFeatured: true,
    isOnSale: true,
    discount: 34,
    techStack: ['React', 'TypeScript', 'Tailwind CSS', 'Recharts', 'React Router'],
    demoUrl: 'https://demo.themeshopy.com/nexus',
    status: 'active',
  },
  {
    id: 'prod_2',
    title: 'Aurora - Landing Page Kit',
    slug: 'aurora-landing-page-kit',
    description: 'Stunning landing page templates with 20+ sections, animations, and conversion-optimized layouts.',
    longDescription: 'Aurora is a premium landing page kit featuring 20+ beautifully designed sections. Each section is carefully crafted for maximum conversion rates. Includes hero sections, feature showcases, pricing tables, testimonials, and more.',
    price: 29,
    originalPrice: undefined,
    category: 'Landing Pages',
    categorySlug: 'landing-pages',
    sellerId: 'user_seller_2',
    sellerName: 'Stella Rodriguez',
    sellerAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&h=150&fit=crop&crop=face',
    thumbnail: thumbnailBases[0],
    images: [thumbnailBases[0], thumbnailBases[4], thumbnailBases[5]],
    tags: ['landing', 'react', 'animations', 'conversion'],
    rating: 4.8,
    reviewCount: 156,
    sales: 920,
    downloads: 950,
    license: 'regular',
    licensePrice: 89,
    version: '2.0.0',
    lastUpdated: '2024-06-05',
    createdAt: '2023-11-20',
    isNew: false,
    isTrending: true,
    isFeatured: true,
    isOnSale: false,
    techStack: ['React', 'Framer Motion', 'Tailwind CSS'],
    demoUrl: 'https://demo.themeshopy.com/aurora',
    status: 'active',
  },
  {
    id: 'prod_3',
    title: 'Cosmos - WordPress Business Theme',
    slug: 'cosmos-wordpress-business-theme',
    description: 'Multi-purpose WordPress theme with 15 demos, Elementor support, and WooCommerce integration.',
    longDescription: 'Cosmos is a versatile WordPress theme perfect for businesses, agencies, and creative professionals. Features 15 complete demo sites, full Elementor page builder support, WooCommerce ready, and extensive customization options.',
    price: 49,
    category: 'WordPress Themes',
    categorySlug: 'wordpress-themes',
    sellerId: 'user_seller_3',
    sellerName: 'David Kim',
    sellerAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face',
    thumbnail: thumbnailBases[2],
    images: [thumbnailBases[2], thumbnailBases[6], thumbnailBases[7]],
    tags: ['wordpress', 'business', 'elementor', 'woocommerce'],
    rating: 4.7,
    reviewCount: 203,
    sales: 1560,
    downloads: 1610,
    license: 'regular',
    licensePrice: 129,
    version: '4.1.0',
    lastUpdated: '2024-05-28',
    createdAt: '2023-06-10',
    isNew: false,
    isTrending: false,
    isFeatured: true,
    isOnSale: false,
    techStack: ['WordPress', 'PHP', 'Elementor', 'WooCommerce'],
    demoUrl: 'https://demo.themeshopy.com/cosmos',
    status: 'active',
  },
  {
    id: 'prod_4',
    title: 'Prism UI - React Component Library',
    slug: 'prism-ui-react-component-library',
    description: '200+ beautiful React components with Figma design system and full TypeScript support.',
    longDescription: 'Prism UI is a comprehensive React component library featuring 200+ production-ready components. Built with accessibility in mind, full TypeScript support, dark mode, and a matching Figma design system.',
    price: 79,
    category: 'UI Kits',
    categorySlug: 'ui-kits',
    sellerId: 'user_seller_4',
    sellerName: 'Priya Patel',
    sellerAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop&crop=face',
    thumbnail: thumbnailBases[3],
    images: [thumbnailBases[3], thumbnailBases[8], thumbnailBases[9]],
    tags: ['react', 'components', 'figma', 'typescript', 'ui-kit'],
    rating: 4.9,
    reviewCount: 342,
    sales: 2103,
    downloads: 2200,
    license: 'regular',
    licensePrice: 199,
    version: '5.0.2',
    lastUpdated: '2024-06-12',
    createdAt: '2023-04-20',
    isNew: false,
    isTrending: true,
    isFeatured: true,
    isOnSale: false,
    techStack: ['React', 'TypeScript', 'Storybook', 'Figma'],
    demoUrl: 'https://demo.themeshopy.com/prism',
    status: 'active',
  },
  {
    id: 'prod_5',
    title: 'LaunchKit - SaaS Boilerplate',
    slug: 'launchkit-saas-boilerplate',
    description: 'Full-stack SaaS starter with Next.js, Stripe billing, auth, and multi-tenant architecture.',
    longDescription: 'LaunchKit is the ultimate SaaS boilerplate that lets you ship your product in days, not months. Includes complete authentication, Stripe subscription billing, multi-tenant architecture, email notifications, and a beautiful admin dashboard.',
    price: 149,
    originalPrice: 199,
    category: 'SaaS Boilerplates',
    categorySlug: 'saas-boilerplates',
    sellerId: 'user_seller_1',
    sellerName: 'Alex Johnson',
    sellerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face',
    thumbnail: thumbnailBases[4],
    images: [thumbnailBases[4], thumbnailBases[10], thumbnailBases[11]],
    tags: ['saas', 'nextjs', 'stripe', 'auth', 'typescript'],
    rating: 4.8,
    reviewCount: 98,
    sales: 423,
    downloads: 450,
    license: 'regular',
    licensePrice: 399,
    version: '2.3.0',
    lastUpdated: '2024-06-08',
    createdAt: '2024-01-15',
    isNew: false,
    isTrending: true,
    isFeatured: false,
    isOnSale: true,
    discount: 25,
    techStack: ['Next.js', 'TypeScript', 'Prisma', 'Stripe', 'NextAuth'],
    demoUrl: 'https://demo.themeshopy.com/launchkit',
    status: 'active',
  },
  {
    id: 'prod_6',
    title: 'Vibrant - Flutter E-Commerce Kit',
    slug: 'vibrant-flutter-ecommerce-kit',
    description: 'Complete Flutter e-commerce app template with 40+ screens, animations, and backend integration.',
    longDescription: 'Vibrant is a premium Flutter e-commerce kit featuring 40+ beautifully designed screens. Includes product listing, cart, checkout, order tracking, user profile, and more. Ready to connect with your backend.',
    price: 69,
    category: 'Flutter Templates',
    categorySlug: 'flutter-templates',
    sellerId: 'user_seller_2',
    sellerName: 'Stella Rodriguez',
    sellerAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&h=150&fit=crop&crop=face',
    thumbnail: thumbnailBases[5],
    images: [thumbnailBases[5], thumbnailBases[0], thumbnailBases[1]],
    tags: ['flutter', 'ecommerce', 'mobile', 'dart'],
    rating: 4.6,
    reviewCount: 87,
    sales: 340,
    downloads: 360,
    license: 'regular',
    licensePrice: 179,
    version: '1.5.0',
    lastUpdated: '2024-05-20',
    createdAt: '2024-02-10',
    isNew: false,
    isTrending: false,
    isFeatured: false,
    isOnSale: false,
    techStack: ['Flutter', 'Dart', 'GetX', 'Hive'],
    demoUrl: 'https://demo.themeshopy.com/vibrant',
    status: 'active',
  },
  {
    id: 'prod_7',
    title: 'Stellar - React Portfolio Template',
    slug: 'stellar-react-portfolio-template',
    description: 'Beautiful portfolio template for designers and developers with smooth animations.',
    longDescription: 'Stellar is a modern portfolio template built with React and Framer Motion. Features smooth page transitions, animated skill bars, project showcases, blog section, and contact form. Perfect for designers and developers.',
    price: 19,
    category: 'React Templates',
    categorySlug: 'react-templates',
    sellerId: 'user_seller_3',
    sellerName: 'David Kim',
    sellerAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face',
    thumbnail: thumbnailBases[6],
    images: [thumbnailBases[6], thumbnailBases[2], thumbnailBases[3]],
    tags: ['react', 'portfolio', 'framer-motion', 'animations'],
    rating: 4.7,
    reviewCount: 124,
    sales: 780,
    downloads: 810,
    license: 'regular',
    licensePrice: 49,
    version: '1.2.0',
    lastUpdated: '2024-04-15',
    createdAt: '2023-10-05',
    isNew: false,
    isTrending: false,
    isFeatured: false,
    isOnSale: false,
    techStack: ['React', 'Framer Motion', 'Tailwind CSS', 'TypeScript'],
    demoUrl: 'https://demo.themeshopy.com/stellar',
    status: 'active',
  },
  {
    id: 'prod_8',
    title: 'DataVault - Analytics Dashboard',
    slug: 'datavault-analytics-dashboard',
    description: 'Professional analytics dashboard with real-time charts, data tables, and export features.',
    longDescription: 'DataVault is a premium analytics dashboard template packed with interactive charts, data tables, filtering capabilities, and export features. Built with React, Recharts, and TanStack Table for maximum performance.',
    price: 89,
    originalPrice: 119,
    category: 'Admin Templates',
    categorySlug: 'admin-templates',
    sellerId: 'user_seller_1',
    sellerName: 'Alex Johnson',
    sellerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face',
    thumbnail: thumbnailBases[7],
    images: [thumbnailBases[7], thumbnailBases[4], thumbnailBases[5]],
    tags: ['analytics', 'dashboard', 'charts', 'react', 'typescript'],
    rating: 4.8,
    reviewCount: 167,
    sales: 634,
    downloads: 660,
    license: 'regular',
    licensePrice: 249,
    version: '2.1.0',
    lastUpdated: '2024-06-01',
    createdAt: '2024-01-20',
    isNew: false,
    isTrending: true,
    isFeatured: false,
    isOnSale: true,
    discount: 25,
    techStack: ['React', 'TypeScript', 'Recharts', 'TanStack Table'],
    demoUrl: 'https://demo.themeshopy.com/datavault',
    status: 'active',
  },
  {
    id: 'prod_9',
    title: 'IconFlow - 5000+ SVG Icons Pack',
    slug: 'iconflow-5000-svg-icons',
    description: 'Massive icon library with 5000+ SVG icons in 6 styles, Figma plugin included.',
    longDescription: 'IconFlow is the most comprehensive icon library available, featuring 5000+ carefully crafted SVG icons in 6 different styles. Includes a Figma plugin for seamless design workflow, React components, and individual SVG files.',
    price: 39,
    category: 'Design Assets',
    categorySlug: 'design-assets',
    sellerId: 'user_seller_4',
    sellerName: 'Priya Patel',
    sellerAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop&crop=face',
    thumbnail: thumbnailBases[8],
    images: [thumbnailBases[8], thumbnailBases[9], thumbnailBases[10]],
    tags: ['icons', 'svg', 'figma', 'design', 'react'],
    rating: 4.9,
    reviewCount: 456,
    sales: 3240,
    downloads: 3400,
    license: 'regular',
    licensePrice: 99,
    version: '7.0.0',
    lastUpdated: '2024-06-14',
    createdAt: '2022-12-01',
    isNew: false,
    isTrending: true,
    isFeatured: true,
    isOnSale: false,
    techStack: ['SVG', 'React', 'Figma', 'TypeScript'],
    demoUrl: 'https://demo.themeshopy.com/iconflow',
    status: 'active',
  },
  {
    id: 'prod_10',
    title: 'MailCraft - Email Template System',
    slug: 'mailcraft-email-template-system',
    description: '50+ responsive HTML email templates with drag-and-drop builder and dark mode support.',
    longDescription: 'MailCraft is a comprehensive email template system featuring 50+ responsive HTML templates. Compatible with all major email clients, drag-and-drop builder, dark mode support, and integration with popular email services.',
    price: 35,
    category: 'Email Templates',
    categorySlug: 'email-templates',
    sellerId: 'user_seller_2',
    sellerName: 'Stella Rodriguez',
    sellerAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&h=150&fit=crop&crop=face',
    thumbnail: thumbnailBases[9],
    images: [thumbnailBases[9], thumbnailBases[11], thumbnailBases[0]],
    tags: ['email', 'html', 'responsive', 'mailchimp', 'sendgrid'],
    rating: 4.7,
    reviewCount: 213,
    sales: 1890,
    downloads: 1950,
    license: 'regular',
    licensePrice: 89,
    version: '3.0.0',
    lastUpdated: '2024-05-10',
    createdAt: '2023-03-15',
    isNew: false,
    isTrending: false,
    isFeatured: false,
    isOnSale: false,
    techStack: ['HTML', 'CSS', 'MJML'],
    demoUrl: 'https://demo.themeshopy.com/mailcraft',
    status: 'active',
  },
  {
    id: 'prod_11',
    title: 'Horizon - Next.js Website Theme',
    slug: 'horizon-nextjs-website-theme',
    description: 'Modern Next.js 14 theme with App Router, MDX blog, dark mode, and SEO optimization.',
    longDescription: 'Horizon is a production-ready Next.js 14 website theme built with the App Router. Features an integrated MDX blog system, dark mode, comprehensive SEO optimization, Contentful CMS integration, and blazing fast performance.',
    price: 55,
    originalPrice: 75,
    category: 'Website Themes',
    categorySlug: 'website-themes',
    sellerId: 'user_seller_3',
    sellerName: 'David Kim',
    sellerAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face',
    thumbnail: thumbnailBases[10],
    images: [thumbnailBases[10], thumbnailBases[1], thumbnailBases[2]],
    tags: ['nextjs', 'blog', 'seo', 'typescript', 'website'],
    rating: 4.8,
    reviewCount: 178,
    sales: 876,
    downloads: 920,
    license: 'regular',
    licensePrice: 149,
    version: '2.4.0',
    lastUpdated: '2024-06-09',
    createdAt: '2024-01-05',
    isNew: true,
    isTrending: false,
    isFeatured: false,
    isOnSale: true,
    discount: 27,
    techStack: ['Next.js 14', 'TypeScript', 'MDX', 'Tailwind CSS', 'Contentful'],
    demoUrl: 'https://demo.themeshopy.com/horizon',
    status: 'active',
  },
  {
    id: 'prod_12',
    title: 'WooShop - WooCommerce Plugin Bundle',
    slug: 'wooshop-woocommerce-plugin-bundle',
    description: 'Bundle of 12 premium WooCommerce plugins to supercharge your online store.',
    longDescription: 'WooShop is the ultimate WooCommerce plugin bundle featuring 12 premium plugins. Includes abandoned cart recovery, advanced filtering, bulk pricing, loyalty points, subscription manager, and more.',
    price: 99,
    category: 'Plugins',
    categorySlug: 'plugins',
    sellerId: 'user_seller_3',
    sellerName: 'David Kim',
    sellerAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face',
    thumbnail: thumbnailBases[11],
    images: [thumbnailBases[11], thumbnailBases[6], thumbnailBases[7]],
    tags: ['woocommerce', 'wordpress', 'plugins', 'ecommerce'],
    rating: 4.6,
    reviewCount: 134,
    sales: 567,
    downloads: 590,
    license: 'regular',
    licensePrice: 249,
    version: '5.2.0',
    lastUpdated: '2024-05-25',
    createdAt: '2023-07-20',
    isNew: false,
    isTrending: false,
    isFeatured: false,
    isOnSale: false,
    techStack: ['PHP', 'WordPress', 'WooCommerce', 'jQuery'],
    demoUrl: 'https://demo.themeshopy.com/wooshop',
    status: 'active',
  },
  {
    id: 'prod_13',
    title: 'FlowChat - AI Chatbot Source Code',
    slug: 'flowchat-ai-chatbot-source-code',
    description: 'Full-stack AI chatbot application with GPT integration, multi-model support, and billing.',
    longDescription: 'FlowChat is a production-ready AI chatbot platform source code. Features multi-model support (GPT-4, Claude), conversation history, team workspaces, usage analytics, Stripe billing, and a beautiful responsive interface.',
    price: 199,
    originalPrice: 299,
    category: 'Source Code',
    categorySlug: 'source-code',
    sellerId: 'user_seller_1',
    sellerName: 'Alex Johnson',
    sellerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face',
    thumbnail: thumbnailBases[0],
    images: [thumbnailBases[0], thumbnailBases[8], thumbnailBases[9]],
    tags: ['ai', 'chatbot', 'gpt', 'saas', 'react', 'nodejs'],
    rating: 4.9,
    reviewCount: 67,
    sales: 234,
    downloads: 250,
    license: 'extended',
    licensePrice: 599,
    version: '1.8.0',
    lastUpdated: '2024-06-13',
    createdAt: '2024-03-01',
    isNew: true,
    isTrending: true,
    isFeatured: true,
    isOnSale: true,
    discount: 33,
    techStack: ['React', 'Node.js', 'PostgreSQL', 'OpenAI', 'Stripe', 'Redis'],
    demoUrl: 'https://demo.themeshopy.com/flowchat',
    status: 'active',
  },
  {
    id: 'prod_14',
    title: 'Spark - Startup Landing Page',
    slug: 'spark-startup-landing-page',
    description: 'High-converting startup landing page with A/B testing components and analytics integration.',
    longDescription: 'Spark is designed specifically for startup founders who need to validate their ideas fast. Features multiple hero variations for A/B testing, a built-in analytics dashboard, email capture forms, and integration with Mailchimp and ConvertKit.',
    price: 25,
    category: 'Landing Pages',
    categorySlug: 'landing-pages',
    sellerId: 'user_seller_2',
    sellerName: 'Stella Rodriguez',
    sellerAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&h=150&fit=crop&crop=face',
    thumbnail: thumbnailBases[1],
    images: [thumbnailBases[1], thumbnailBases[10], thumbnailBases[11]],
    tags: ['landing', 'startup', 'ab-testing', 'react'],
    rating: 4.7,
    reviewCount: 89,
    sales: 445,
    downloads: 470,
    license: 'regular',
    licensePrice: 69,
    version: '1.3.0',
    lastUpdated: '2024-04-20',
    createdAt: '2024-02-25',
    isNew: true,
    isTrending: false,
    isFeatured: false,
    isOnSale: false,
    techStack: ['React', 'TypeScript', 'Tailwind CSS', 'Framer Motion'],
    demoUrl: 'https://demo.themeshopy.com/spark',
    status: 'active',
  },
  {
    id: 'prod_15',
    title: 'PulseKit - Healthcare UI Kit',
    slug: 'pulsekit-healthcare-ui-kit',
    description: 'Specialized UI kit for healthcare apps with HIPAA-compliant component patterns.',
    longDescription: 'PulseKit is a comprehensive UI kit designed specifically for healthcare applications. Features 150+ components including patient records, appointment scheduling, medical charts, and HIPAA-compliant data display patterns.',
    price: 89,
    category: 'UI Kits',
    categorySlug: 'ui-kits',
    sellerId: 'user_seller_4',
    sellerName: 'Priya Patel',
    sellerAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop&crop=face',
    thumbnail: thumbnailBases[2],
    images: [thumbnailBases[2], thumbnailBases[5], thumbnailBases[6]],
    tags: ['healthcare', 'ui-kit', 'figma', 'react', 'medical'],
    rating: 4.8,
    reviewCount: 56,
    sales: 178,
    downloads: 190,
    license: 'regular',
    licensePrice: 229,
    version: '1.1.0',
    lastUpdated: '2024-05-30',
    createdAt: '2024-04-10',
    isNew: true,
    isTrending: false,
    isFeatured: false,
    isOnSale: false,
    techStack: ['React', 'TypeScript', 'Figma', 'Tailwind CSS'],
    demoUrl: 'https://demo.themeshopy.com/pulsekit',
    status: 'active',
  },
  {
    id: 'prod_16',
    title: 'VeloxAdmin - Vue 3 Dashboard',
    slug: 'veloxadmin-vue3-dashboard',
    description: 'Fast and feature-rich Vue 3 admin dashboard with Pinia, Vite, and 60+ pages.',
    longDescription: 'VeloxAdmin is a high-performance Vue 3 dashboard template. Built with Vite for blazing fast development, Pinia for state management, and includes 60+ pre-built pages covering everything you need for a complete admin panel.',
    price: 49,
    category: 'Admin Templates',
    categorySlug: 'admin-templates',
    sellerId: 'user_seller_3',
    sellerName: 'David Kim',
    sellerAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face',
    thumbnail: thumbnailBases[3],
    images: [thumbnailBases[3], thumbnailBases[7], thumbnailBases[8]],
    tags: ['vue', 'dashboard', 'pinia', 'vite', 'typescript'],
    rating: 4.6,
    reviewCount: 143,
    sales: 567,
    downloads: 600,
    license: 'regular',
    licensePrice: 129,
    version: '3.0.1',
    lastUpdated: '2024-05-15',
    createdAt: '2023-09-10',
    isNew: false,
    isTrending: false,
    isFeatured: false,
    isOnSale: false,
    techStack: ['Vue 3', 'TypeScript', 'Pinia', 'Vite', 'Vueuse'],
    demoUrl: 'https://demo.themeshopy.com/veloxadmin',
    status: 'active',
  },
  {
    id: 'prod_17',
    title: 'Flexa - Responsive HTML Landing Page',
    slug: 'flexa-responsive-html-landing-page',
    description: 'Ultra-fast HTML5 and CSS3 single page template with Tailwind CSS and grid layouts.',
    longDescription: 'Flexa is a lightweight, responsive static HTML5 landing page template. Clean HTML structure, fully commented CSS, SEO optimized, and extremely easy to configure. Uses semantic markup and modern animation transitions.',
    price: 19,
    category: 'HTML Templates',
    categorySlug: 'html-templates',
    sellerId: 'user_seller_1',
    sellerName: 'Alex Johnson',
    sellerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face',
    thumbnail: thumbnailBases[5],
    images: [thumbnailBases[5], thumbnailBases[6]],
    tags: ['html', 'css', 'landing', 'responsive'],
    rating: 4.7,
    reviewCount: 48,
    sales: 120,
    downloads: 130,
    license: 'regular',
    licensePrice: 49,
    version: '1.2.0',
    lastUpdated: '2024-06-15',
    createdAt: '2024-02-10',
    isNew: true,
    isTrending: false,
    isFeatured: true,
    isOnSale: false,
    techStack: ['HTML5', 'CSS3', 'JavaScript', 'Tailwind CSS'],
    demoUrl: 'https://demo.themeshopy.com/flexa',
    status: 'active',
  },
  {
    id: 'prod_18',
    title: 'SwiftPay - iOS Payment App Template',
    slug: 'swiftpay-ios-payment-app-template',
    description: 'Clean Swift and SwiftUI design files and code assets for an iOS banking application.',
    longDescription: 'SwiftPay is a premium iOS app template designed for mobile banking and payment applications. Written 100% in SwiftUI with interactive diagrams, charts, face ID integrations, dark mode support, and clean animations.',
    price: 69,
    category: 'Mobile App Templates',
    categorySlug: 'mobile-app-templates',
    sellerId: 'user_seller_2',
    sellerName: 'Stella Rodriguez',
    sellerAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&h=150&fit=crop&crop=face',
    thumbnail: thumbnailBases[6],
    images: [thumbnailBases[6], thumbnailBases[7]],
    tags: ['swift', 'swiftui', 'ios', 'banking', 'app'],
    rating: 4.9,
    reviewCount: 84,
    sales: 230,
    downloads: 245,
    license: 'regular',
    licensePrice: 199,
    version: '2.1.0',
    lastUpdated: '2024-06-20',
    createdAt: '2024-01-15',
    isNew: false,
    isTrending: true,
    isFeatured: true,
    isOnSale: false,
    techStack: ['SwiftUI', 'Swift', 'Combine', 'Charts'],
    demoUrl: 'https://demo.themeshopy.com/swiftpay',
    status: 'active',
  },
];

// Generate additional 84 products
const extraProductTitles = [
  'Cascade - Tailwind CSS Template', 'Nova - Agency Website Theme', 'Fusion - App Landing Page',
  'Orbit - SaaS Marketing Site', 'Zen - Minimalist Portfolio', 'Echo - Blog Template',
  'Pixel - Creative Studio Theme', 'Wave - Music Platform UI', 'Cloud - Tech Startup Theme',
  'Flame - Restaurant Website', 'Arctic - Photography Theme', 'Summit - Travel App UI',
  'Bloom - Flower Shop Template', 'Cyber - Game Platform Theme', 'Atlas - Map App Source Code',
  'Pronto - Restaurant Ordering App', 'Spark - Fitness App UI', 'Lumen - Education Platform',
  'Vertex - Real Estate App', 'Canvas - Artist Portfolio', 'Mosaic - News Portal Theme',
  'Pulse - Social Media Dashboard', 'Radix - Component Library', 'Lyra - Music Dashboard',
  'Cosmos Dashboard Kit', 'Ember - E-Learning Platform', 'Swift - iOS App Template',
  'Vortex - Weather App UI', 'Spectrum - Color Tool App', 'Helix - Biotech Landing Page',
];

for (let i = 0; i < 30; i++) {
  const sellers = ['user_seller_1', 'user_seller_2', 'user_seller_3', 'user_seller_4'];
  const sellerNames = ['Alex Johnson', 'Stella Rodriguez', 'David Kim', 'Priya Patel'];
  const sellerSeeds = ['seller1', 'seller2', 'seller3', 'seller4'];
  const categories = [
    { name: 'Website Themes', slug: 'website-themes' },
    { name: 'Admin Templates', slug: 'admin-templates' },
    { name: 'React Templates', slug: 'react-templates' },
    { name: 'UI Kits', slug: 'ui-kits' },
    { name: 'Landing Pages', slug: 'landing-pages' },
    { name: 'Design Assets', slug: 'design-assets' },
  ];
  const si = i % 4;
  const ci = i % categories.length;
  const cat = categories[ci];
  const basePrice = [19, 29, 39, 49, 59, 69, 79, 89][i % 8];
  const id = `prod_extra_${i + 1}`;
  mockProducts.push({
    id,
    title: extraProductTitles[i] || `Premium Template ${i + 17}`,
    slug: (extraProductTitles[i] || `premium-template-${i + 17}`).toLowerCase().replace(/[^a-z0-9]+/g, '-'),
    description: `A professional ${cat.name.toLowerCase()} template with modern design and extensive customization options.`,
    longDescription: `This premium ${cat.name.toLowerCase()} template is designed for professionals. Features modern design, responsive layout, dark/light mode, and comprehensive documentation to get you started quickly.`,
    price: basePrice,
    originalPrice: i % 5 === 0 ? basePrice + 20 : undefined,
    category: cat.name,
    categorySlug: cat.slug,
    sellerId: sellers[si],
    sellerName: sellerNames[si],
    sellerAvatar: ['https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face','https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&h=150&fit=crop&crop=face','https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face','https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop&crop=face'][si],
    thumbnail: thumbnailBases[i % thumbnailBases.length],
    images: [thumbnailBases[i % thumbnailBases.length]],
    tags: ['react', 'tailwind', 'typescript'],
    rating: 4.2 + (i % 8) * 0.1,
    reviewCount: 20 + i * 7,
    sales: 50 + i * 25,
    downloads: 55 + i * 27,
    license: 'regular',
    licensePrice: basePrice * 2.5,
    version: '1.0.0',
    lastUpdated: '2024-05-01',
    createdAt: '2024-01-01',
    isNew: i < 5,
    isTrending: i % 7 === 0,
    isFeatured: false,
    isOnSale: i % 6 === 0,
    discount: i % 6 === 0 ? 20 : undefined,
    techStack: ['React', 'TypeScript', 'Tailwind CSS'],
    status: 'active',
  });
}
