import type { Review } from '@/types';

export const mockReviews: Review[] = [
  {
    id: 'rev_1',
    productId: 'prod_1',
    userId: 'user_buyer_1',
    userName: 'Sarah Williams',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=buyer1',
    rating: 5,
    title: 'Absolutely stunning dashboard template!',
    comment: 'I have been using Nexus for 3 months now and I am blown away by the quality. The components are well-documented, the code is clean, and the design is top-notch. Support from Alex is also exceptional.',
    createdAt: '2024-05-15',
    helpful: 47,
    verified: true,
  },
  {
    id: 'rev_2',
    productId: 'prod_1',
    userId: 'user_agency_1',
    userName: 'Digital Nexus Agency',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=agency1',
    rating: 5,
    title: 'Best dashboard template we have ever used',
    comment: 'We use Nexus across multiple client projects and it saves us weeks of development time. The customization options are endless and the TypeScript types are properly defined.',
    createdAt: '2024-04-20',
    helpful: 31,
    verified: true,
  },
  {
    id: 'rev_3',
    productId: 'prod_4',
    userId: 'user_buyer_1',
    userName: 'Sarah Williams',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=buyer1',
    rating: 5,
    title: 'The most comprehensive UI kit available',
    comment: 'Prism UI has everything I need. 200+ components, excellent Figma integration, and the code quality is superb. Definitely worth every penny.',
    createdAt: '2024-05-01',
    helpful: 29,
    verified: true,
  },
  {
    id: 'rev_4',
    productId: 'prod_9',
    userId: 'user_buyer_1',
    userName: 'Sarah Williams',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=buyer1',
    rating: 5,
    title: 'The only icon pack you will ever need',
    comment: '5000+ icons and they are all perfectly consistent. The Figma plugin is a game changer. I use IconFlow on every project now.',
    createdAt: '2024-06-01',
    helpful: 56,
    verified: true,
  },
  {
    id: 'rev_5',
    productId: 'prod_2',
    userId: 'user_agency_1',
    userName: 'Digital Nexus Agency',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=agency1',
    rating: 4,
    title: 'Great landing page kit',
    comment: 'Aurora has beautiful animations and the sections are well-designed. Would love a few more section options but overall very happy with the purchase.',
    createdAt: '2024-05-10',
    helpful: 18,
    verified: true,
  },
  {
    id: 'rev_6',
    productId: 'prod_5',
    userId: 'user_buyer_1',
    userName: 'Sarah Williams',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=buyer1',
    rating: 5,
    title: 'Saved me months of development',
    comment: 'LaunchKit is incredible. I launched my SaaS in 2 weeks using this boilerplate. The Stripe integration, auth, and multi-tenant setup are all production-ready.',
    createdAt: '2024-06-05',
    helpful: 42,
    verified: true,
  },
  {
    id: 'rev_7',
    productId: 'prod_13',
    userId: 'user_agency_1',
    userName: 'Digital Nexus Agency',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=agency1',
    rating: 5,
    title: 'Production-ready AI chatbot',
    comment: 'FlowChat is incredibly well-architected. The multi-model support, team workspaces, and billing integration are all working perfectly out of the box.',
    createdAt: '2024-06-10',
    helpful: 28,
    verified: true,
  },
];
