import type { User } from '@/types';

export const mockUsers: User[] = [
  {
    id: 'user_admin_1',
    email: 'admin@themeshopy.com',
    password: 'Password123',
    name: 'Admin User',
    role: 'admin',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin',
    bio: 'Platform administrator with full access to all features.',
    location: 'San Francisco, CA',
    joinedAt: '2023-01-01',
    isVerified: true,
    earnings: 0,
    totalSales: 0,
    totalPurchases: 0,
  },
  {
    id: 'user_seller_1',
    email: 'seller@themeshopy.com',
    password: 'Password123',
    name: 'Alex Johnson',
    role: 'seller',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=seller1',
    bio: 'Professional UI/UX designer with 8+ years of experience creating premium digital products.',
    website: 'https://alexjohnson.design',
    location: 'Austin, TX',
    joinedAt: '2023-03-15',
    isVerified: true,
    earnings: 24680,
    totalSales: 1247,
    totalPurchases: 12,
  },
  {
    id: 'user_buyer_1',
    email: 'buyer@themeshopy.com',
    password: 'Password123',
    name: 'Sarah Williams',
    role: 'buyer',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=buyer1',
    bio: 'Frontend developer passionate about beautiful user interfaces.',
    location: 'New York, NY',
    joinedAt: '2023-06-10',
    isVerified: true,
    earnings: 0,
    totalSales: 0,
    totalPurchases: 23,
  },
  {
    id: 'user_affiliate_1',
    email: 'affiliate@themeshopy.com',
    password: 'Password123',
    name: 'Mike Chen',
    role: 'affiliate',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=affiliate1',
    bio: 'Digital marketing specialist focused on SaaS products.',
    website: 'https://mikechenmarketing.com',
    location: 'Seattle, WA',
    joinedAt: '2023-04-20',
    isVerified: true,
    earnings: 3420,
    referralCode: 'MIKE20',
    commissionRate: 30,
    totalPurchases: 5,
  },
  {
    id: 'user_agency_1',
    email: 'agency@themeshopy.com',
    password: 'Password123',
    name: 'Digital Nexus Agency',
    role: 'agency',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=agency1',
    bio: 'Full-service digital agency specializing in web development and design.',
    website: 'https://digitalnexus.agency',
    location: 'Chicago, IL',
    joinedAt: '2023-02-28',
    isVerified: true,
    earnings: 0,
    totalSales: 0,
    totalPurchases: 87,
    teamSize: 24,
  },
  {
    id: 'user_seller_2',
    email: 'stella@themeshopy.com',
    password: 'Password123',
    name: 'Stella Rodriguez',
    role: 'seller',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=seller2',
    bio: 'React specialist building premium SaaS templates and admin dashboards.',
    website: 'https://stelladev.io',
    location: 'Miami, FL',
    joinedAt: '2023-05-01',
    isVerified: true,
    earnings: 18900,
    totalSales: 934,
    totalPurchases: 8,
  },
  {
    id: 'user_seller_3',
    email: 'david@themeshopy.com',
    password: 'Password123',
    name: 'David Kim',
    role: 'seller',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=seller3',
    bio: 'WordPress developer and theme creator with 5+ years experience.',
    location: 'Boston, MA',
    joinedAt: '2023-07-12',
    isVerified: true,
    earnings: 12450,
    totalSales: 620,
    totalPurchases: 3,
  },
  {
    id: 'user_seller_4',
    email: 'priya@themeshopy.com',
    password: 'Password123',
    name: 'Priya Patel',
    role: 'seller',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=seller4',
    bio: 'UI Kit designer specializing in Figma and React component libraries.',
    location: 'San Jose, CA',
    joinedAt: '2023-08-05',
    isVerified: true,
    earnings: 9870,
    totalSales: 490,
    totalPurchases: 14,
  },
];
